# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  prefer-h3: false # æ˜¯å¦å¼€å¯ DoH æ”¯æŒ HTTP/3ï¼Œå°†å¹¶å‘å°è¯•
  respect-rules: true
  # æ¨¡å¼åˆ‡æ¢ redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  # æ¨¡å¼åˆ‡æ¢ whitelist/blacklist 
  # é»‘åå•æ¨¡å¼è¡¨ç¤ºå¦‚æœåŒ¹é…æˆåŠŸåˆ™ä¸è¿”å› Fake-IP, ç™½åå•æ¨¡å¼æ—¶åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å› Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:fakeip_filter_domain"
    - "geosite:cn,category-games@cn,private"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - quic://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query 
  nameserver:
    - quic://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query

proxies: 
  - name: "ğŸŸ¢ ç›´è¿"
    type: direct
    udp: true        

# é”šç‚¹åŒº
Proxy_first: &Proxy_first {type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©, é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, å…¨çƒç›´è¿]}

Direct_first: &Direct_first {type: select, proxies: [å…¨çƒç›´è¿, èŠ‚ç‚¹é€‰æ‹©,  é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹]}

Include_all: &Include_all {type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©, é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, å…¨çƒç›´è¿], include-all: true, exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)"}



# ç­–ç•¥ç»„
proxy-groups:
  - {name: èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, æ•…éšœè½¬ç§»], icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/select.png"}
# åŠŸèƒ½å‹ä»£ç†ç»„é»˜è®¤éšè— start
  - {name: ğŸŸ¢ ç›´è¿, type: select, hidden: true, proxies: [DIRECT]}
  - {name: ğŸ”— ä»£ç†, type: select, hidden: true, proxies: [èŠ‚ç‚¹é€‰æ‹©]}
# over
  - {name: YouTube, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/youtube.png"}
  - {name: Google, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/google.png"}
  - {name: Meta, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/meta.png"}
  - {name: AI, <<: *Include_all, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/ai.png"}
  - {name: GitHub, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/github.png"}
  - {name: OneDrive, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/onedrive.png"}
  - {name: Microsoft, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/microsoft.png"}
  - {name: Telegram, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/telegram.png"}
  - {name: TikTok, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/tiktok.png"}
  - {name: NETFLIX, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/netfix.png"}
  - {name: DisneyPlus, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/disneyplus.png"}
  - {name: HBO, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/hbo.png"}
  - {name: Apple, type: select, <<: *Direct_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/apple.png"}
  - {name: Emby,type: select, <<: *Include_all, include-all: true, icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/emby.png}
  - {name: å“”å“©å“”å“©, type: select, <<: *Direct_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/bilibili.png"}
  - {name: å“”å“©ä¸œå—äºš, type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©, æ–°åŠ å¡èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, å…¨çƒç›´è¿], icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/bilibilit.png"}
  - {name: å·´å“ˆå§†ç‰¹, type: select, proxies: [å°æ¹¾èŠ‚ç‚¹], icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/bahamut.png"}
  - {name: Spotify, <<: *Proxy_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/spotify.png"}
  - {name: å›½å†…åª’ä½“, type: select, <<: *Direct_first, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Chinese_media.png"}
  - {name: STEAM,type: select, <<: *Include_all, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/steam.png"}
  - {name: å…¨çƒç›´è¿, type: select, proxies: [ğŸŸ¢ ç›´è¿, ğŸ”— ä»£ç†], icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/direct.png"}
  - {name: éšç§æ‹¦æˆª, type: select, proxies: [ğŸš« æ‹’ç», âšª ä¸¢å¼ƒ ,ğŸŸ¢ ç›´è¿, ğŸ”— ä»£ç†], icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/block.png"}
  - {name: Final, type: select, <<: *Include_all,  icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/final.png"}
  - {name: è‡ªå»º/å®¶å®½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(è‡ªå»º|CF|The_house|private)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/private_node.png"}
  - {name: é¦™æ¸¯èŠ‚ç‚¹, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨, é¦™æ¸¯å‡è¡¡], include-all: true, filter: "(?i)(æ¸¯|hk|hongkong|Hong Kong)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Hongkong.png"}
  - {name: æ–°åŠ å¡èŠ‚ç‚¹, type: select, proxies: [æ–°åŠ å¡è‡ªåŠ¨, æ–°åŠ å¡å‡è¡¡], include-all: true, filter: "(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|singapore)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Singapore.png"}
  - {name: æ—¥æœ¬èŠ‚ç‚¹, type: select, proxies: [æ—¥æœ¬è‡ªåŠ¨, æ—¥æœ¬å‡è¡¡], include-all: true, filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Japan.png"}
  - {name: å°æ¹¾èŠ‚ç‚¹, type: select, proxies: [å°æ¹¾è‡ªåŠ¨, å°æ¹¾å‡è¡¡], include-all: true, filter: "(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Taiwan_China.png"}
  - {name: ç¾å›½èŠ‚ç‚¹, type: select, proxies: [ç¾å›½è‡ªåŠ¨, ç¾å›½å‡è¡¡], include-all: true, filter: "(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|United States)" ,exclude-filter: "(?i)(Australia|Russia)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/America.png"}
  - {name: æ¬§æ´²èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(ğŸ‡¦ğŸ‡±|ğŸ‡¦ğŸ‡©|ğŸ‡¦ğŸ‡¹|ğŸ‡§ğŸ‡¾|ğŸ‡§ğŸ‡ª|ğŸ‡§ğŸ‡¦|ğŸ‡§ğŸ‡¬|ğŸ‡­ğŸ‡·|ğŸ‡¨ğŸ‡¾|ğŸ‡¨ğŸ‡¿|ğŸ‡©ğŸ‡°|ğŸ‡ªğŸ‡ª|ğŸ‡«ğŸ‡®|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡¬ğŸ‡·|ğŸ‡­ğŸ‡º|ğŸ‡®ğŸ‡¸|ğŸ‡®ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡½ğŸ‡°|ğŸ‡±ğŸ‡»|ğŸ‡±ğŸ‡®|ğŸ‡±ğŸ‡¹|ğŸ‡±ğŸ‡º|ğŸ‡²ğŸ‡¹|ğŸ‡²ğŸ‡©|ğŸ‡²ğŸ‡¨|ğŸ‡²ğŸ‡ª|ğŸ‡³ğŸ‡±|ğŸ‡²ğŸ‡°|ğŸ‡³ğŸ‡´|ğŸ‡µğŸ‡±|ğŸ‡µğŸ‡¹|ğŸ‡·ğŸ‡´|ğŸ‡·ğŸ‡º|ğŸ‡¸ğŸ‡²|ğŸ‡·ğŸ‡¸|ğŸ‡¸ğŸ‡°|ğŸ‡¸ğŸ‡®|ğŸ‡ªğŸ‡¸|ğŸ‡¸ğŸ‡ª|ğŸ‡¨ğŸ‡­|ğŸ‡¹ğŸ‡·|ğŸ‡ºğŸ‡¦|ğŸ‡¬ğŸ‡§|ğŸ‡»ğŸ‡¦)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/European.png"}
  - {name: é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, hidden: true, filter: "(?i)(é¦™æ¸¯|hk|hongkong|Hong Kong)" ,exclude-filter: "(?i)(The_HK_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png"}
  - {name: æ–°åŠ å¡è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, hidden: true, filter: "(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|Singapore)" ,exclude-filter: "(?i)(The_SG_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png"}
  - {name: æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, hidden: true, filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan)" ,exclude-filter: "(?i)(The_JP_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png"}
  - {name: å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, hidden: true, filter: "(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan)" ,exclude-filter: "(?i)(The_TW_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png"}
  - {name: ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, hidden: true, filter: "(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|united States)" ,exclude-filter: "(?i)(The_US_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|russia|austria|plus|traffic|Australia|rus|aus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png"}
  - {name: é¦™æ¸¯å‡è¡¡, type: load-balance, include-all: true, strategy: sticky-sessions, hidden: true, filter: "(?i)(é¦™æ¸¯|hk|hongkong|Hong Kong)" ,exclude-filter: "(?i)(The_HK_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png"}
  - {name: æ–°åŠ å¡å‡è¡¡, type: load-balance, include-all: true, strategy: consistent-hashing, hidden: true, filter: "(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|Singapore)" ,exclude-filter: "(?i)(The_SG_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png"}
  - {name: æ—¥æœ¬å‡è¡¡, type: load-balance, include-all: true, strategy: consistent-hashing, hidden: true, filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan)" ,exclude-filter: "(?i)(The_JP_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png"}
  - {name: å°æ¹¾å‡è¡¡, type: load-balance, include-all: true, strategy: consistent-hashing, hidden: true, filter: "(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan)" ,exclude-filter: "(?i)(The_TW_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png"}
  - {name: ç¾å›½å‡è¡¡, type: load-balance, include-all: true, strategy: consistent-hashing, hidden: true, filter: "(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|united States)" ,exclude-filter: "(?i)(The_US_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|russia|austria|plus|traffic|Australia|rus|aus)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png"}
  - {name: æ•…éšœè½¬ç§», type: fallback, include-all: true, proxies: [é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹], interval: 300, exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/fallback.png"}
  - {name: å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true, tolerance: 20, interval: 300, exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/all.png"}
  - {name: GLOBAL, type: select, include-all: true , proxies: [èŠ‚ç‚¹é€‰æ‹©, YouTube, Google, Meta, AI, GitHub, OneDrive, Microsoft, Telegram, TikTok, NETFLIX, DisneyPlus, HBO, Apple, Emby, å“”å“©å“”å“©, å“”å“©ä¸œå—äºš, å·´å“ˆå§†ç‰¹, Spotify, å›½å†…åª’ä½“, STEAM, å…¨çƒç›´è¿, éšç§æ‹¦æˆª, Final, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, é¦™æ¸¯è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨, é¦™æ¸¯å‡è¡¡, æ–°åŠ å¡å‡è¡¡, æ—¥æœ¬å‡è¡¡, å°æ¹¾å‡è¡¡, ç¾å›½å‡è¡¡, æ•…éšœè½¬ç§», å…¨éƒ¨èŠ‚ç‚¹], exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)", icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/global.png"}
rules: 
  - GEOSITE,private,å…¨çƒç›´è¿
  - GEOIP,private,å…¨çƒç›´è¿,no-resolve
  - GEOSITE,category-games@cn,å…¨çƒç›´è¿
  - GEOSITE,category-public-tracker,å…¨çƒç›´è¿
  - GEOSITE,openai,AI
  - GEOSITE,category-ai-!cn,AI
  - RULE-SET,ai_domain,AI
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOIP,google,Google,no-resolve
  - GEOSITE,github,GitHub
  - GEOSITE,onedrive,OneDrive
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,apple,Apple
  - GEOSITE,telegram,Telegram
  - GEOIP,telegram,Telegram,no-resolve
  - GEOSITE,facebook,Meta
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,disney,DisneyPlus
  - GEOSITE,hbo,HBO
  - RULE-SET,emby_domain,Emby
  - GEOSITE,spotify,Spotify
  - GEOSITE,bahamut,å·´å“ˆå§†ç‰¹
  - GEOSITE,tiktok,TikTok
  - GEOSITE,bilibili,å“”å“©å“”å“©
  - RULE-SET,bilibili_ip,å“”å“©å“”å“©,no-resolve
  - GEOSITE,biliintl,å“”å“©ä¸œå—äºš
  - GEOSITE,category-media-cn,å›½å†…åª’ä½“
  - GEOSITE,steam,STEAM
  - GEOIP,twitter,èŠ‚ç‚¹é€‰æ‹©,no-resolve
  - GEOIP,ai,AI,no-resolve
  - GEOSITE,gfw,èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,geolocation-!cn,èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,cn,å…¨çƒç›´è¿
  - GEOIP,private,å…¨çƒç›´è¿,no-resolve
  - GEOIP,cn,å…¨çƒç›´è¿,no-resolve
  - MATCH,Final
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  ip_text: &ip_text {type: http, interval: 86400, behavior: ipcidr, format: text}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
  domain_text: &domain_text {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: yaml}
  class_text: &class_text {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  emby_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/emby.yaml" }
  ai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/ai.yaml" }
  fakeip_filter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/fakeip-filter.yaml" }
  bilibili_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/bilibili.yaml" }